# Generated by Django 2.2 on 2020-02-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='product_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
